INCLUDE "levels/level_items.inc"
INCLUDE "include/constants.inc"

	SECTION "LevelItems", DATA, BANK[1]
	
Level0Items:
	DB ITEM_BUBBLE, 34, 18 
	DB ITEM_BUBBLE, 57, 5 
	DB ITEM_HEART, 57, 26
	DB ITEM_NONE
	
Level1Items:
	DB ITEM_BUBBLE, 3, 5 
	DB ITEM_NONE 
	
Level2Items: 
	DB ITEM_BUBBLE, 22, 46 
	DB ITEM_BUBBLE, 2, 89 
	DB ITEM_HEART, 13, 122 
	DB ITEM_NONE 
	
Level3Items:
	DB ITEM_HEART, 11, 52 
	DB ITEM_BUBBLE, 5, 122 
	DB ITEM_BUBBLE, 7, 122 
	DB ITEM_BUBBLE, 6, 121 
	DB ITEM_BUBBLE, 83, 9 
	DB ITEM_NONE 
	
	
	