IF !DEF(LEVEL_ENEMIES_INC)
LEVEL_ENEMIES_INC SET 1 

GLOBAL Level0Enemies
GLOBAL Level1Enemies
GLOBAL Level2Enemies
GLOBAL Level3Enemies
GLOBAL Level4Enemies
GLOBAL Level5Enemies
GLOBAL Level6Enemies
GLOBAL Level7Enemies
GLOBAL Level8Enemies
GLOBAL Level9Enemies
GLOBAL Level10Enemies
GLOBAL Level11Enemies 
GLOBAL Level12Enemies
GLOBAL Level13Enemies
GLOBAL Level14Enemies
GLOBAL Level15Enemies
GLOBAL Level16Enemies
GLOBAL Level17Enemies
GLOBAL Level18Enemies
GLOBAL Level19Enemies
GLOBAL Level20Enemies
GLOBAL Level21Enemies
GLOBAL Level22Enemies
GLOBAL Level23Enemies
GLOBAL Level24Enemies

ENDC 