; BULLET_TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : BulletTiles
;   Bank                 : 1
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 1
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "BulletTiles", DATA, BANK[1]

; Start of tile array.
BulletTiles::
DB $70,$70,$F8,$88,$F8,$88,$F8,$88
DB $70,$70,$00,$00,$00,$00,$00,$00
DB $38,$38,$44,$7C,$92,$EE,$AA,$C6
DB $92,$EE,$44,$7C,$38,$38,$00,$00

; End of BULLET_TILES.Z80
