; SPRITE_TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : SpriteTiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 16 x 16
;   Tiles                : 0 to 15
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "PlayerSpriteTiles", HOME

; Start of tile array.
PlayerSpriteTiles::
DB $00,$00,$00,$00,$02,$02,$13,$13
DB $18,$1B,$00,$0F,$00,$0D,$00,$0D
DB $40,$4F,$C0,$C7,$05,$4E,$07,$4C
DB $03,$6C,$03,$3C,$05,$06,$06,$06
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$80,$00,$C0,$04,$A4,$04,$B8
DB $38,$C0,$00,$C0,$90,$70,$D0,$30
DB $C0,$20,$D0,$30,$B0,$70,$00,$00
DB $00,$00,$00,$00,$02,$02,$13,$13
DB $18,$1B,$00,$0F,$00,$0D,$00,$0D
DB $40,$4F,$C0,$C7,$01,$4E,$07,$4C
DB $07,$6C,$03,$3C,$0D,$0E,$08,$08
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$80,$00,$C0,$04,$A4,$04,$B8
DB $38,$C0,$00,$C0,$80,$60,$D0,$30
DB $D0,$30,$C0,$20,$A0,$60,$30,$30
DB $00,$00,$00,$00,$02,$02,$13,$13
DB $18,$1B,$00,$0F,$00,$0D,$00,$0D
DB $00,$0F,$02,$07,$05,$0E,$03,$0C
DB $03,$0C,$03,$3C,$C5,$E6,$4C,$4C
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$80,$00,$C0,$04,$A4,$04,$B8
DB $38,$C0,$08,$C8,$90,$70,$C0,$20
DB $C0,$20,$C0,$20,$A0,$60,$60,$60
DB $00,$00,$00,$00,$02,$02,$13,$13
DB $18,$1B,$00,$0F,$00,$0D,$00,$0D
DB $00,$0F,$20,$27,$65,$6E,$07,$2C
DB $03,$2C,$03,$3C,$05,$06,$06,$06
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$80,$00,$C0,$04,$A4,$04,$B8
DB $38,$C0,$00,$C0,$90,$70,$D0,$30
DB $C0,$20,$C0,$20,$A0,$60,$30,$30

; End of SPRITE_TILES.Z80
